version: '3.1'

services:
  redis:
    container_name: redis-test
    image: redis
    restart: always
    ports:
      - 6379:6379
  mysql:
    container_name: mysql-test
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test1234
